Repository L1ght-time/dark-project-ts, pull requests merged in 2022-03, with the labels that each got.

#14 [refactor] - DPT-066 - Refactoring project
  src/App.tsx
  src/components/layout/Layout/component.tsx
  src/components/layout/Layout/styles.ts
  src/components/layout/components/Header/index.tsx
  src/components/layout/components/Header/styles.ts
  src/components/layout/components/Header/types.ts
  src/components/layout/components/SideBar/SideBarController/NestedItem/component.tsx
  src/components/layout/components/SideBar/SideBarController/NestedItem/index.ts
  src/components/layout/components/SideBar/SideBarController/SingleItem/component.tsx
  src/components/layout/components/SideBar/SideBarController/SingleItem/index.ts
  src/components/layout/components/SideBar/SideBarController/component.tsx
  src/components/layout/components/SideBar/SideBarController/helpers.ts
  src/components/layout/components/SideBar/SideBarController/index.ts
  src/components/layout/components/SideBar/SideBarList/ListItem/component.tsx
  src/components/layout/components/SideBar/SideBarList/ListItem/index.ts
  src/components/layout/components/SideBar/SideBarList/index.ts
  src/components/layout/components/SideBar/component.tsx
  src/components/layout/components/SideBar/constants.ts
  src/components/layout/components/SideBar/types.ts
  src/constants.ts
  src/constants/routes/authRoutes.ts
  src/constants/routes/constants.ts
  src/constants/routes/nonAuthRoutes.ts
  src/routes/authRoutes/index.ts
  src/routes/nonAuthRoutes/index.ts
Labels: reviewed, ✔MK

#16 [feature] DPT-019 - Create TextFieldFormik
  src/components/formik/FieldFormikText/component.tsx
  src/components/formik/FieldFormikText/types.ts
  src/constants/routes/authRoutes.ts
  src/pages/Field/component.tsx
  src/pages/Field/mock.ts
  src/pages/Field/types.ts
Labels: reviewed, ✔NL

#17 [feature] DPT-021 - Demonstration additions phones with FieldArray
  .eslintrc.json
  src/components/formik/FieldArrayFormik/component.tsx
  src/components/formik/FieldArrayFormik/styles.ts
  src/components/formik/FieldArrayFormik/types.ts
  src/components/formik/FieldFormikText/component.tsx
  src/components/formik/FieldFormikText/types.ts
  src/components/shared/DisplayFormikStateData/component.tsx
  src/components/shared/DisplayFormikStateData/index.ts
  src/components/shared/DisplayFormikStateData/types.ts
  src/constants/routes/authRoutes.ts
  src/pages/Field/component.tsx
  src/pages/Field/constants.ts
  src/pages/Field/index.ts
  src/pages/Field/mocks.ts
  src/pages/FieldArray/component.tsx
  src/pages/FieldArray/index.ts
  src/pages/index.ts
  yarn.lock
Labels: need review
